// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import App from './App'
import { defaultSettings, LEGACY_SETTINGS_STORAGE_KEY, SETTINGS_STORAGE_KEY } from './lib/settings'
import type { RepoProject } from './types'

const storage = vi.hoisted(() => ({ loadWorkspace: vi.fn(), loadFavorites: vi.fn(), saveWorkspace: vi.fn(), saveFavorites: vi.fn(), loadProjectTags: async () => ({}), saveProjectTags: vi.fn(), clearWorkspace: vi.fn() }))
vi.mock('./lib/storage', () => ({ ...storage, loadCommitActivity: async () => undefined, saveCommitActivity: async () => {} }))
const project: RepoProject = {
  id: 'alpha', name: 'Alpha', dirName: 'alpha', relativePath: '.', description: '', stack: ['React', 'TypeScript', 'Vite'], scripts: {}, packageManager: 'npm', scannedAt: '2026-10-08T12:00:00Z',
  audit: { manager: 'npm', scannedAt: '2026-10-08T12:00:00Z', counts: { critical: 0, high: 1, moderate: 0, low: 0, info: 0 }, findings: [{ name: 'example', severity: 'high', title: 'Example finding' }] },
  outdated: { manager: 'npm', scannedAt: '2026-10-08T12:00:00Z', score: 20, level: 'moderate', findings: [{ name: 'example', current: '1.0.0', latest: '3.0.0', change: 'major', majorGap: 2, score: 20 }] },
}
let preferences: Map<string, string>
let setItem: ReturnType<typeof vi.fn>

beforeEach(() => {
  vi.resetAllMocks()
  preferences = new Map()
  setItem = vi.fn((key: string, value: string) => { preferences.set(key, value) })
  vi.stubGlobal('localStorage', { getItem: (key: string) => preferences.get(key) ?? null, setItem })
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue({ ok: true, json: async () => ({ ok: true }) }))
  storage.loadWorkspace.mockResolvedValue({ rootName: 'Projects', mode: 'browser', projects: [project], syncedAt: project.scannedAt })
  storage.loadFavorites.mockResolvedValue([])
})
afterEach(() => { cleanup(); vi.unstubAllGlobals() })

async function setup() {
  const result = render(<App />)
  await screen.findByRole('button', { name: 'View Alpha' })
  return { ...result, user: userEvent.setup() }
}
const auditBadge = () => screen.getByRole('button', { name: /Alpha: 1 vulnerability/ })
const outdatedBadge = () => screen.getByRole('button', { name: /Alpha: 1 outdated package/ })

describe('workspace settings dialog', () => {
  it('saves, reloads, cancels, and clears the optional heatmap author', async () => {
    const { user, unmount } = await setup()
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('tab', { name: 'Interface' }))
    const field = screen.getByRole('textbox', { name: 'Author email (optional)' })
    await user.type(field, 'alice@example.com')
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!).commitActivityAuthor).toBe('alice@example.com')
    unmount()
    await setup()
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('tab', { name: 'Interface' }))
    expect((screen.getByRole('textbox', { name: 'Author email (optional)' }) as HTMLInputElement).value).toBe('alice@example.com')
    await user.clear(screen.getByRole('textbox', { name: 'Author email (optional)' }))
    await user.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!).commitActivityAuthor).toBe('alice@example.com')
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('tab', { name: 'Interface' }))
    await user.clear(screen.getByRole('textbox', { name: 'Author email (optional)' }))
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!).commitActivityAuthor).toBe('')
  })

  it('saves application choices, updates both action surfaces, and restores choices after reload', async () => {
    vi.stubGlobal('fetch', vi.fn(async (url: string) => ({ ok: true, json: async () => url.endsWith('/history') ? { available: false, branches: [], authors: [], commits: [], total: 0, offset: 0, hasMore: false, activity: [], from: '', to: '', shallow: false } : { ok: true } })))
    storage.loadWorkspace.mockResolvedValue({ rootName: 'Projects', rootPath: '/projects', mode: 'helper', projects: [project], syncedAt: project.scannedAt })
    const { user, unmount } = await setup()
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('tab', { name: 'Applications' }))
    expect((screen.getByRole('combobox', { name: 'Code editor' }) as HTMLSelectElement).value).toBe('vscode')
    expect((screen.getByRole('combobox', { name: 'Git client' }) as HTMLSelectElement).value).toBe('sourcetree')
    await user.selectOptions(screen.getByRole('combobox', { name: 'Code editor' }), 'cursor')
    expect((screen.getByRole('combobox', { name: 'Script terminal' }) as HTMLSelectElement).value).toBe('auto')
    await user.selectOptions(screen.getByRole('combobox', { name: 'Script terminal' }), 'iterm2')
    await user.selectOptions(screen.getByRole('combobox', { name: 'Git client' }), 'fork')
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!)).toMatchObject({ editor: 'cursor', gitClient: 'fork', terminal: 'iterm2' })
    await user.click(screen.getByRole('button', { name: 'Actions for Alpha' }))
    expect(screen.queryByRole('menuitem', { name: 'Open in VS Code' })).toBeNull()
    expect(screen.getByRole('menuitem', { name: 'Open in Fork' })).toBeTruthy()
    await user.click(screen.getByRole('menuitem', { name: 'Open in Cursor' }))
    expect(fetch).toHaveBeenCalledWith('/api/projects/alpha/open', expect.objectContaining({ body: JSON.stringify({ app: 'cursor' }) }))
    await screen.findByText('Open request sent to your computer.')
    await user.click(screen.getByRole('button', { name: 'View Alpha' }))
    const details = screen.getByRole('dialog', { name: 'Alpha' })
    expect(within(details).getByRole('button', { name: 'Cursor', exact: true })).toBeTruthy()
    await user.click(within(details).getByRole('button', { name: 'Fork', exact: true }))
    expect(fetch).toHaveBeenCalledWith('/api/projects/alpha/open', expect.objectContaining({ body: JSON.stringify({ app: 'fork' }) }))
    unmount()
    await setup()
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('tab', { name: 'Applications' }))
    expect((screen.getByRole('combobox', { name: 'Code editor' }) as HTMLSelectElement).value).toBe('cursor')
    expect((screen.getByRole('combobox', { name: 'Git client' }) as HTMLSelectElement).value).toBe('fork')
    expect((screen.getByRole('combobox', { name: 'Script terminal' }) as HTMLSelectElement).value).toBe('iterm2')
    await user.selectOptions(screen.getByRole('combobox', { name: 'Code editor' }), 'zed')
    await user.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!).editor).toBe('cursor')
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('button', { name: 'Reset defaults' }))
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!)).toMatchObject({ editor: 'vscode', gitClient: 'sourcetree' })
  })

  it('keeps customized application actions behind the helper connection flow', async () => {
    preferences.set(SETTINGS_STORAGE_KEY, JSON.stringify({ ...defaultSettings, editor: 'zed', gitClient: 'gitkraken' }))
    const { user } = await setup()
    await user.click(screen.getByRole('button', { name: 'Actions for Alpha' }))
    await user.click(screen.getByRole('menuitem', { name: 'Open in Zed' }))
    expect(await screen.findByRole('dialog')).toBeTruthy()
    expect(vi.mocked(fetch).mock.calls.some(([url]) => String(url).endsWith('/open'))).toBe(false)
  })

  it('shows technologies beyond the old default and remembers a newly chosen smaller limit', async () => {
    preferences.set(LEGACY_SETTINGS_STORAGE_KEY, JSON.stringify({ ...defaultSettings, sidebarTechnologyLimit: 7, colorScheme: 'sand' }))
    storage.loadWorkspace.mockResolvedValue({ rootName: 'Projects', mode: 'browser', projects: [{ ...project, stack: Array.from({ length: 12 }, (_, index) => `Technology ${index + 1}`) }], syncedAt: project.scannedAt })
    const { user, unmount } = await setup()
    const technologyButtons = () => within(screen.getByRole('navigation', { name: 'Filter by technology' })).getAllByRole('button')
    expect(technologyButtons()).toHaveLength(12)
    expect(document.documentElement.dataset.colorScheme).toBe('sand')
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('tab', { name: 'Interface' }))
    const limit = screen.getByRole('spinbutton', { name: 'Technologies in sidebar' })
    expect((limit as HTMLInputElement).value).toBe('50')
    await user.clear(limit)
    await user.type(limit, '7')
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(technologyButtons()).toHaveLength(7)
    unmount()
    await setup()
    expect(technologyButtons()).toHaveLength(7)
    expect(document.documentElement.dataset.colorScheme).toBe('sand')
  })

  it('validates, saves and restores a custom push-reminder time and disabled preference', async () => {
    const { user, unmount } = await setup()
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('tab', { name: 'Interface' }))
    expect((screen.getByLabelText('Reminder time') as HTMLInputElement).value).toBe('18:00')
    fireEvent.change(screen.getByLabelText('Reminder time'), { target: { value: '' } })
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(screen.getByText('Choose a valid reminder time.')).toBeTruthy()
    fireEvent.change(screen.getByLabelText('Reminder time'), { target: { value: '17:30' } })
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!)).toMatchObject({ pushReminderTime: '17:30', pushReminderEnabled: true })
    unmount()
    await setup()
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('tab', { name: 'Interface' }))
    expect((screen.getByLabelText('Reminder time') as HTMLInputElement).value).toBe('17:30')
    await user.click(screen.getByRole('checkbox', { name: 'Remind me to push changes to origin' }))
    expect((screen.getByLabelText('Reminder time') as HTMLInputElement).disabled).toBe(true)
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!)).toMatchObject({ pushReminderTime: '17:30', pushReminderEnabled: false })
  })

  it('saves a scheme with other settings, restores it on reload, and keeps it when switching modes', async () => {
    const { user, unmount } = await setup()
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('tab', { name: 'Interface' }))
    const forest = screen.getByRole('radio', { name: 'Forest' })
    expect((forest as HTMLInputElement).checked).toBe(true)
    await user.click(screen.getByRole('radio', { name: 'Ocean' }))
    expect((screen.getByRole('radio', { name: 'Ocean' }) as HTMLInputElement).checked).toBe(true)
    expect(document.documentElement.dataset.colorScheme).toBe('forest')
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!)).toEqual({ ...defaultSettings, colorScheme: 'ocean' })
    expect(document.documentElement.dataset.colorScheme).toBe('ocean')
    for (const mode of ['dark', 'light', 'system']) {
      await user.selectOptions(screen.getByRole('combobox', { name: 'Color theme' }), mode)
      expect(document.documentElement.dataset.colorScheme).toBe('ocean')
      if (mode !== 'system') expect(document.documentElement.dataset.theme).toBe(mode)
    }
    unmount()
    await setup()
    expect(document.documentElement.dataset.colorScheme).toBe('ocean')
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('tab', { name: 'Interface' }))
    expect((screen.getByRole('radio', { name: 'Ocean' }) as HTMLInputElement).checked).toBe(true)
  })

  it('discards scheme drafts and failed saves, resets only on save, and follows other tabs', async () => {
    preferences.set(SETTINGS_STORAGE_KEY, JSON.stringify({ ...defaultSettings, colorScheme: 'plum' }))
    const { user } = await setup()
    const openInterface = async () => {
      await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
      await user.click(screen.getByRole('tab', { name: 'Interface' }))
    }
    await openInterface()
    await user.click(screen.getByRole('radio', { name: 'Sand' }))
    await user.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(document.documentElement.dataset.colorScheme).toBe('plum')
    await openInterface()
    expect((screen.getByRole('radio', { name: 'Plum' }) as HTMLInputElement).checked).toBe(true)
    await user.click(screen.getByRole('radio', { name: 'Sand' }))
    setItem.mockImplementationOnce(() => { throw new Error('Storage blocked') })
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(screen.getByRole('alert').textContent).toContain('Could not save settings')
    expect(document.documentElement.dataset.colorScheme).toBe('plum')
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!).colorScheme).toBe('plum')
    await user.click(screen.getByRole('button', { name: 'Reset defaults' }))
    expect(document.documentElement.dataset.colorScheme).toBe('plum')
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(document.documentElement.dataset.colorScheme).toBe('forest')
    act(() => {
      preferences.set(SETTINGS_STORAGE_KEY, JSON.stringify({ ...defaultSettings, colorScheme: 'sand' }))
      window.dispatchEvent(new StorageEvent('storage', { key: SETTINGS_STORAGE_KEY }))
    })
    expect(document.documentElement.dataset.colorScheme).toBe('sand')
    act(() => {
      preferences.clear()
      window.dispatchEvent(new StorageEvent('storage', { key: null }))
    })
    expect(document.documentElement.dataset.colorScheme).toBe('forest')
  })

  it('saves watcher mode, cadence and selected checks, validates intervals, and restores the draft', async () => {
    const { user, unmount } = await setup()
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('tab', { name: 'Watcher' }))
    expect((screen.getByRole('combobox', { name: 'Scan mode' }) as HTMLSelectElement).value).toBe('manual')
    for (const name of ['React Doctor', 'Lighthouse']) {
      const checkbox = screen.getByRole('checkbox', { name, exact: true }) as HTMLInputElement
      expect(checkbox.checked).toBe(false)
      expect(checkbox.disabled).toBe(true)
    }
    await user.selectOptions(screen.getByRole('combobox', { name: 'Scan mode' }), 'periodic')
    await user.clear(screen.getByRole('spinbutton', { name: 'Scan interval (minutes)' }))
    await user.type(screen.getByRole('spinbutton', { name: 'Scan interval (minutes)' }), '0')
    await user.click(screen.getByRole('tab', { name: 'Interface' }))
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(screen.getByRole('tab', { name: 'Watcher' }).getAttribute('aria-selected')).toBe('true')
    expect(screen.getByRole('spinbutton', { name: 'Scan interval (minutes)' }).getAttribute('aria-invalid')).toBe('true')
    await user.clear(screen.getByRole('spinbutton', { name: 'Scan interval (minutes)' }))
    await user.type(screen.getByRole('spinbutton', { name: 'Scan interval (minutes)' }), '30')
    await user.click(screen.getByRole('checkbox', { name: 'Outdated packages', exact: true }))
    await user.click(screen.getByRole('checkbox', { name: 'React Doctor', exact: true }))
    await user.click(screen.getByRole('checkbox', { name: 'Lighthouse', exact: true }))
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!)).toMatchObject({ watcherMode: 'periodic', watcherIntervalMinutes: 30, watcherOutdated: false, watcherReactDoctor: true, watcherLighthouse: true })
    unmount()
    await setup()
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('tab', { name: 'Watcher' }))
    expect((screen.getByRole('combobox', { name: 'Scan mode' }) as HTMLSelectElement).value).toBe('periodic')
    for (const name of ['React Doctor', 'Lighthouse']) expect((screen.getByRole('checkbox', { name, exact: true }) as HTMLInputElement).checked).toBe(true)
    await user.selectOptions(screen.getByRole('combobox', { name: 'Scan mode' }), 'changes')
    expect(screen.getByRole('spinbutton', { name: 'Check for package changes (seconds)' })).toBeTruthy()
    await user.click(screen.getByRole('checkbox', { name: 'Lighthouse', exact: true }))
    await user.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!)).toMatchObject({ watcherMode: 'periodic', watcherReactDoctor: true, watcherLighthouse: true })
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('tab', { name: 'Watcher' }))
    await user.selectOptions(screen.getByRole('combobox', { name: 'Scan mode' }), 'changes')
    await user.click(screen.getByRole('checkbox', { name: 'Lighthouse', exact: true }))
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!)).toMatchObject({ watcherMode: 'changes', watcherReactDoctor: true, watcherLighthouse: false })
  })

  it('keeps batch totals and package badges in sync when score weights change', async () => {
    const workspace = { rootName: 'Projects', rootPath: '/projects', mode: 'helper', projects: [project], syncedAt: project.scannedAt }
    storage.loadWorkspace.mockResolvedValue(workspace)
    vi.stubGlobal('fetch', vi.fn(async (url: string) => ({ ok: true, json: async () => url === '/api/scan' ? workspace : url.endsWith('/outdated') ? { outdated: project.outdated } : { ok: true } })))
    const { user } = await setup()
    await user.click(screen.getByRole('button', { name: 'Scan outdated packages', exact: true }))
    await screen.findByText('Outdated-package scan complete')
    expect(screen.getByText('20 total lag points')).toBeTruthy()
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByText('Score weights', { selector: 'summary' }))
    await user.clear(screen.getByRole('spinbutton', { name: 'Points per major version' }))
    await user.type(screen.getByRole('spinbutton', { name: 'Points per major version' }), '15')
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(screen.getByText('30 total lag points')).toBeTruthy()
    expect(outdatedBadge().textContent).toBe('30')
  })

  it('updates cached badge colors, details and filter results, and persists across reloads', async () => {
    const { user, unmount } = await setup()
    expect(auditBadge().classList.contains('audit-color-red')).toBe(true)
    expect(outdatedBadge().classList.contains('outdated-level-moderate')).toBe(true)
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    const dialog = screen.getByRole('dialog', { name: 'Settings' })
    await user.selectOptions(within(dialog).getByRole('combobox', { name: 'High severity color' }), 'orange')
    await user.clear(within(dialog).getByRole('spinbutton', { name: 'Red at score' }))
    await user.type(within(dialog).getByRole('spinbutton', { name: 'Red at score' }), '20')
    await user.click(within(dialog).getByRole('button', { name: 'Save settings' }))
    expect(screen.queryByRole('dialog')).toBeNull()
    expect(document.activeElement).toBe(screen.getByRole('button', { name: 'Settings', exact: true }))
    expect(auditBadge().classList.contains('audit-color-orange')).toBe(true)
    expect(outdatedBadge().classList.contains('outdated-level-high')).toBe(true)
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!)).toMatchObject({ outdatedRedScore: 20, auditColors: { high: 'orange' } })
    await user.click(screen.getByRole('button', { name: /^All filters/ }))
    await user.selectOptions(screen.getByRole('combobox', { name: 'Outdated packages' }), 'high')
    expect(screen.getAllByRole('article')).toHaveLength(1)
    await user.selectOptions(screen.getByRole('combobox', { name: 'Vulnerabilities' }), 'red')
    expect(screen.queryAllByRole('article')).toHaveLength(0)
    await user.click(screen.getByRole('button', { name: 'Clear filters', exact: true }))
    await user.click(outdatedBadge())
    const details = screen.getByRole('dialog', { name: 'Alpha' })
    expect(within(details).getByText(/Red requires at least 20 points/)).toBeTruthy()
    await user.click(within(details).getByRole('tab', { name: 'Vulnerabilities' }))
    expect(details.querySelector('.severity-high')?.classList.contains('audit-color-orange')).toBe(true)
    unmount()
    await setup()
    expect(auditBadge().classList.contains('audit-color-orange')).toBe(true)
    expect(outdatedBadge().classList.contains('outdated-level-high')).toBe(true)
  })

  it('keeps drafts isolated, validates hidden categories, and restores defaults only when saved', async () => {
    const { user } = await setup()
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.clear(screen.getByRole('spinbutton', { name: 'Red at score' }))
    await user.type(screen.getByRole('spinbutton', { name: 'Red at score' }), '5')
    await user.click(screen.getByRole('tab', { name: 'Interface' }))
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(screen.getByRole('tab', { name: 'Badges & scores' }).getAttribute('aria-selected')).toBe('true')
    expect(screen.getByRole('spinbutton', { name: 'Red at score' }).getAttribute('aria-invalid')).toBe('true')
    expect(screen.getByRole('alert').textContent).toContain('Correct')
    expect(preferences.has(SETTINGS_STORAGE_KEY)).toBe(false)
    await user.click(screen.getByRole('button', { name: 'Cancel' }))
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    expect((screen.getByRole('spinbutton', { name: 'Red at score' }) as HTMLInputElement).value).toBe('100')
    await user.click(screen.getByRole('tab', { name: 'Interface' }))
    await user.clear(screen.getByRole('spinbutton', { name: 'Technology tags per project' }))
    await user.type(screen.getByRole('spinbutton', { name: 'Technology tags per project' }), '0')
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(screen.getByRole('article').querySelectorAll('.project-tags .technology-tag')).toHaveLength(0)
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    await user.click(screen.getByRole('button', { name: 'Reset defaults' }))
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(screen.getByRole('article').querySelectorAll('.project-tags .technology-tag')).toHaveLength(3)
    expect(JSON.parse(preferences.get(SETTINGS_STORAGE_KEY)!)).toEqual(defaultSettings)
  })

  it('reports persistence failures without applying unsaved changes and supports keyboard tab navigation', async () => {
    const { user } = await setup()
    await user.click(screen.getByRole('button', { name: 'Settings', exact: true }))
    screen.getByRole('tab', { name: 'Badges & scores' }).focus()
    await user.keyboard('{ArrowRight}')
    expect(document.activeElement).toBe(screen.getByRole('tab', { name: 'Filter thresholds' }))
    await user.keyboard('{End}')
    expect(document.activeElement).toBe(screen.getByRole('tab', { name: 'Backup' }))
    await user.keyboard('{Home}')
    await user.selectOptions(screen.getByRole('combobox', { name: 'High severity color' }), 'blue')
    setItem.mockImplementation(() => { throw new Error('Storage blocked') })
    await user.click(screen.getByRole('button', { name: 'Save settings' }))
    expect(screen.getByRole('alert').textContent).toContain('Could not save settings')
    await user.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(auditBadge().classList.contains('audit-color-red')).toBe(true)
  })
})
